# The CI-config of Dindo

# 不同的测试样例

env:
  - DOCUMENT=true
#  - CABALVER=1.22 GHCVER=7.10.3

services:
  - docker

before_install:
  - bash dindo-test/before_install.sh

script: |
  if [ -n "$DOCUMENT" ]; then
    dindo-test/document-build.sh
  else
    dindo-test/compiler-test.sh
    dindo-test/docker-build.sh
  fi
after_success: |
  dindo-test/after_success.sh
