# The CI-config of Dindo

# 不同的测试样例

env:
  - DOCUMENT=true
  - CABALVER=1.22 GHCVER=7.10.3 BUILDPART=dindo-um

services:
  - docker

before_install:
  - source dindo-test/before_install.sh

script: |
  if [ -n "$DOCUMENT" ]; then
    source dindo-test/document-build.sh
  else
    source dindo-test/compiler-test.sh
    source dindo-test/docker-build.sh
  fi
after_success: |
  cd $TRAVIS_BUILD_DIR
  source dindo-test/after-success.sh
