flags: {}
extra-package-dbs: []
packages:
- dindo-common/
- dindo-database/
- dindo-launch/
- dindo-tools/
- dindo-usrmanage/
- dindo-agentake/
- persistent-postgresql/
extra-deps: []
resolver: nightly-2016-05-27
